services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    deploy:
      resources:
        limits:
          memory: 4G
    restart: unless-stopped

  jupyter:
    build:
      context: ./reviews-assistant
      dockerfile: Dockerfile.dev
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./reviews-assistant:/home/jovyan/reviews-assistant
    restart: unless-stopped
